from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from forum.models import Course, Block
from forum.services.course_services import course_search
import json
import re
import os
from django.conf import settings
from django.contrib.staticfiles import finders


class Command(BaseCommand):
    help = (
        'Import Course -> Block relationships from a plaintext file. '
        'Each non-empty line should be: "Course Name: 1B,1C, ..."'
    )

    def add_arguments(self, parser):
        parser.add_argument('filepath', nargs='?', default=None, help='Path to the plaintext file to import (optional)')
        parser.add_argument('--dry-run', action='store_true', help='Parse and report actions but do not modify the DB')
        parser.add_argument(
            '--dry-run-output',
            default=None,
            help='Path for the comparison file generated by --dry-run (defaults to <input>.dry-run.txt)',
        )
        parser.add_argument('--create-blocks', action='store_true', help='Create Block records if missing')
        parser.add_argument('--force', action='store_true', help='Apply mappings even if multiple course matches exist (uses first match)')

    def handle(self, *args, **options):
        path = options['filepath']

        # If no filepath provided, try to find the default file in staticfiles
        if not path:
            found = finders.find('forum/Untitled.txt')
            if found:
                path = found
            else:
                # Fallback to repository-relative path using BASE_DIR
                path = os.path.join(settings.BASE_DIR, 'forum', 'static', 'forum', 'Untitled.txt')
        dry_run = options['dry_run']
        dry_run_output = options['dry_run_output']
        create_blocks = options['create_blocks']
        force = options['force']

        try:
            with open(path, 'r', encoding='utf-8') as f:
                raw_lines = f.readlines()
        except OSError as e:
            raise CommandError(f'Could not open file: {e}')

        # Basic RTF-stripping: remove braces and backslash control words if present.
        # Prefer to provide a plaintext file, but this helps when the input is a quick RTF dump.
        def sanitize_line(line: str) -> str:
            # Remove common RTF characters and excessive whitespace
            line = re.sub(r'[{}\\].*?\b', '', line)
            return line.strip()

        mappings = []  # list of tuples (course_name, [block_codes])

        for raw in raw_lines:
            line = raw.strip()
            if not line:
                continue
            # Try naive RTF cleanup if the file contains RTF header
            if line.startswith('{\\rtf') or line.startswith('{'):
                # fallback: skip rtf metadata lines
                # but allow content lines further down
                if line.lower().startswith('{\\rtf'):
                    continue
            # If the line contains braces or backslashes it's likely still RTF; do a sanitize
            if '{' in line or '\\' in line:
                line = sanitize_line(line)
                if not line:
                    continue

            # Expect format: Course Name: B1, B2, B3
            if ':' not in line:
                # If no colon, try splitting on tab or multiple spaces
                parts = re.split(r'\t+|\s{2,}', line, maxsplit=1)
            else:
                # Split on the final colon so course names such as
                # "AP World History: Modern" are preserved in full.
                parts = line.rsplit(':', 1)

            if len(parts) < 2:
                self.stdout.write(self.style.WARNING(f"Skipping unrecognized line: {line}"))
                continue

            course_name = parts[0].strip()
            block_part = parts[1].strip()

            # split block codes by comma, semicolon or whitespace
            raw_tokens = re.split(r'[;,]|\s+', block_part)

            # Normalize tokens: uppercase, strip surrounding non-alphanumerics
            # and remove trailing backslashes or other stray chars produced by RTF
            norm_tokens = []
            for tok in raw_tokens:
                t = tok.strip().upper()
                if not t:
                    continue
                # remove non-alphanumeric characters from start/end
                t = re.sub(r'^[^A-Z0-9]+|[^A-Z0-9]+$', '', t)
                if t:
                    norm_tokens.append(t)

            # Keep only tokens that look like canonical block codes (e.g., 1A, 2D)
            block_codes = [b for b in norm_tokens if re.match(r'^[0-9][A-Z]$', b)]

            if not block_codes:
                self.stdout.write(self.style.WARNING(f'No block codes found for "{course_name}" — skipping'))
                continue

            mappings.append((course_name, block_codes))

        if not mappings:
            raise CommandError('No valid mappings parsed from file')

        report = []
        resolved_mappings = []
        comparison_lines = [
            '# Dry run comparison generated from the supplied mapping file.',
            '# Resolved lines show the production Course.name and blocks that would be applied.',
            '# Commented lines were not applied and require review.',
            '',
        ]
        created_blocks = set()
        applied_count = 0
        skipped_count = 0

        if dry_run:
            # NOTICE style isn't provided by BaseCommand.style in some Django versions
            # use WARNING for visibility instead
            self.stdout.write(self.style.WARNING('Dry run: no DB changes will be made'))

        for course_name, block_codes in mappings:
            # 1) Try exact match first (case-insensitive)
            matches = list(Course.objects.filter(name__iexact=course_name))

            # 2) If no exact match, try the service search (trigram/prefix) which
            #    may return close matches for human-entered names. We call
            #    course_search with a mock request object exposing GET['q'].
            if not matches:

                mock_request = type('MockRequest', (), {'GET': {'q': course_name}})()
                try:
                    response = course_search(mock_request)
                    # course_search returns a JsonResponse with a JSON list
                    data = json.loads(response.content)
                    # data is a list of dicts with 'id' and 'name' keys
                    if data:
                        # take up to 3 suggestions from search as potential matches
                        suggested_ids = [d['id'] for d in data[:3]]
                        # fetch Course objects and preserve the ordering returned by course_search
                        matches = list(Course.objects.filter(id__in=suggested_ids))
                        id_order = list(suggested_ids)
                        matches = sorted(matches, key=lambda c: id_order.index(c.id) if c.id in id_order else len(id_order))
                        # Prefer an exact-name match among suggestions (avoid picking 'Honours' when exact exists)
                        exact_in_suggested = [m for m in matches if m.name.strip().lower() == course_name.strip().lower()]
                        if exact_in_suggested:
                            matches = exact_in_suggested
                except Exception as e:
                    print(e)
                    matches = []

            # 3) Fallback to icontains if still no matches
            if not matches:
                matches = list(Course.objects.filter(name__icontains=course_name))

            if not matches:
                report.append((course_name, block_codes, 'COURSE_NOT_FOUND'))
                comparison_lines.append(f'# COURSE_NOT_FOUND: {course_name}: {", ".join(block_codes)}')
                skipped_count += 1
                continue

            if len(matches) > 1 and not force:
                report.append((course_name, block_codes, f'MULTIPLE_COURSES ({len(matches)})'))
                comparison_lines.append(
                    f'# MULTIPLE_COURSES ({len(matches)}): {course_name}: {", ".join(block_codes)}'
                )
                skipped_count += 1
                continue

            course_obj = matches[0]

            # Ensure blocks exist
            block_objs = []
            missing_block_codes = []
            for code in block_codes:
                block_obj = Block.objects.filter(code__iexact=code).first()
                if not block_obj:
                    missing_block_codes.append(code)
                if block_obj:
                    block_objs.append(block_obj)

            if missing_block_codes and not create_blocks:
                comparison_lines.append(
                    f'# BLOCK_NOT_FOUND ({", ".join(missing_block_codes)}): '
                    f'{course_name}: {", ".join(block_codes)}'
                )
                report.append((course_name, block_codes, 'BLOCK_NOT_FOUND'))
                skipped_count += 1
                continue

            resolved_mappings.append((course_obj, block_codes, block_objs))
            if course_obj.name.strip().casefold() != course_name.strip().casefold():
                comparison_lines.append(f'# SOURCE: {course_name}')
            comparison_lines.append(f'{course_obj.name}: {", ".join(block.code for block in block_objs)}')

            if dry_run:
                report.append((course_name, [b.code for b in block_objs], 'WILL_ADD (dry-run)'))
            else:
                report.append((course_name, [b.code for b in block_objs], 'READY'))

        included_course_ids = {course_obj.id for course_obj, _block_codes, _block_objs in resolved_mappings}
        not_added_courses = list(
            Course.objects.exclude(id__in=included_course_ids).order_by('name')
        )

        if dry_run:
            comparison_lines.extend([
                '',
                '# COURSES_NOT_ADDED: existing Course objects not represented in the staged mappings',
            ])
            comparison_lines.extend(f'# {course.name}' for course in not_added_courses)
            output_path = dry_run_output
            if not output_path:
                root, extension = os.path.splitext(path)
                output_path = f'{root}.dry-run{extension or ".txt"}'
            try:
                with open(output_path, 'w', encoding='utf-8') as output_file:
                    output_file.write('\n'.join(comparison_lines) + '\n')
            except OSError as exc:
                raise CommandError(f'Could not write dry-run comparison file: {exc}')
            self.stdout.write(self.style.SUCCESS(f'Dry-run comparison written to {output_path}'))
        elif skipped_count:
            raise CommandError(
                f'Refusing to clear existing mappings because {skipped_count} input mapping(s) could not be resolved. '
                'Run with --dry-run, fix the comparison file, and retry.'
            )
        else:
            through_model = Course.blocks.through
            try:
                with transaction.atomic():
                    existing_rel_count = through_model.objects.count()
                    through_model.objects.all().delete()
                    for course_obj, block_codes, block_objs in resolved_mappings:
                        block_objs_by_code = {block.code: block for block in block_objs}
                        actual_block_objs = []
                        for code in block_codes:
                            block_obj = block_objs_by_code.get(code)
                            if not block_obj:
                                block_obj = Block.objects.create(code=code)
                                created_blocks.add(code)
                            actual_block_objs.append(block_obj)
                        course_obj.blocks.add(*actual_block_objs)
                        self.stdout.write(
                            f"Added blocks for Course(id={course_obj.id}, name={course_obj.name!r}): "
                            f"{[block.code for block in actual_block_objs]}"
                        )
                self.stdout.write(self.style.SUCCESS(
                    f'Replaced {existing_rel_count} existing course<->block mappings'
                ))
                applied_count = len(resolved_mappings)
                report = [
                    (course_name, block_codes, 'ADDED')
                    for course_name, block_codes, _status in report
                ]
            except Exception as exc:
                raise CommandError(f'Failed to replace course<->block mappings: {exc}')

        # Summary
        self.stdout.write('\nImport summary:')
        for item in report:
            name, blocks, status = item
            self.stdout.write(f' - {name!r} -> {blocks} : {status}')

        self.stdout.write('\nTotals:')
        self.stdout.write(f' Applied: {applied_count}')
        self.stdout.write(f' Skipped: {skipped_count}')
        self.stdout.write(f' Course objects not added: {len(not_added_courses)}')
        if created_blocks:
            self.stdout.write(f' Created blocks: {sorted(created_blocks)}')

        not_added = [
            item for item in report
            if item[2] not in {'WILL_ADD (dry-run)', 'READY', 'ADDED'}
        ]
        if not_added:
            self.stdout.write('\nNot added:')
            for name, blocks, status in not_added:
                self.stdout.write(f' - {name!r} -> {blocks} : {status}')

        if dry_run:
            self.stdout.write(self.style.WARNING('Dry run completed — no changes were made. Rerun without --dry-run to apply.'))
