# Generated by Django 4.2.16 on 2025-10-31 23:11

from django.db import migrations, models


def set_existing_user_preferences(apps, schema_editor):
    """Set preferences for existing users: allow_schedule_comparison=True, allow_grade_updates=False"""
    UserProfile = apps.get_model('forum', 'UserProfile')
    # Update existing users to have allow_grade_updates=False (opt-in feature)
    # allow_schedule_comparison defaults to True (existing behavior)
    UserProfile.objects.all().update(allow_grade_updates=False)


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0038_course_max_grade_userprofile_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_grade_updates',
            field=models.BooleanField(default=True, help_text='Enable automatic grade notifications from WolfNet'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_schedule_comparison',
            field=models.BooleanField(default=True, help_text='Allow other users to view and compare your course schedule'),
        ),
        migrations.RunPython(set_existing_user_preferences, reverse_code=migrations.RunPython.noop),
    ]

