# Generated by Django 4.2.16 on 2025-12-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0039_add_user_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='block_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_10_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='block_9_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='early_dismissal',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='late_start',
            field=models.BooleanField(null=True),
        ),
    ]
