# Generated by Django 4.2.16 on 2025-12-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0040_add_block_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lunch_card',
            field=models.ImageField(blank=True, help_text='Upload your lunch card image', null=True, upload_to='lunch_cards/'),
        ),
    ]
