# Generated by Django 4.2.16 on 2026-01-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0041_userprofile_lunch_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Your Instagram username (without @)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL (must start with www.linkedin.com/in/)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snapchat_handle',
            field=models.CharField(blank=True, help_text='Your Snapchat username (without @)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_email',
            field=models.BooleanField(default=False, help_text='Display your email address on your public profile'),
        ),
    ]
