# Generated by Django 4.2.16 on 2026-02-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0042_add_social_media_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_teacher',
            field=models.BooleanField(default=True, help_text='Allow teachers to view this post'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Indicates if this user is a teacher'),
        ),
    ]
