# Generated by Django 4.2.16 on 2026-02-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0043_post_allow_teacher_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
