# Generated by Django 4.2.16 on 2026-02-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0046_user_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerPinMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the pin milestone (e.g., 'Bronze Pin', 'Silver Pin')", max_length=100)),
                ('hours_required', models.PositiveIntegerField(help_text='Number of volunteer hours required to achieve this milestone')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Volunteer Pin Milestone',
                'verbose_name_plural': 'Volunteer Pin Milestones',
                'ordering': ['order', 'hours_required'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_coordinator',
            field=models.BooleanField(default=False, help_text='Indicates if this user can manage volunteer hours and milestones'),
        ),
    ]
