# Generated by Django 4.2.16 on 2026-02-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0047_volunteerpinmilestone_user_volunteer_coordinator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerpinmilestone',
            options={'ordering': ['hours_required'], 'verbose_name': 'Volunteer Pin Milestone', 'verbose_name_plural': 'Volunteer Pin Milestones'},
        ),
        migrations.RemoveField(
            model_name='volunteerpinmilestone',
            name='order',
        ),
        migrations.AddField(
            model_name='volunteerpinmilestone',
            name='has_other_requirements',
            field=models.BooleanField(default=False, help_text='Check if this pin has other requirements beyond volunteer hours'),
        ),
    ]
