# Generated by Django 4.2.16 on 2026-02-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0048_alter_volunteerpinmilestone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the resource (e.g., 'Volunteer Application Form', 'Service Guidelines')", max_length=200)),
                ('url', models.URLField(help_text='URL to the resource', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Optional short description of the resource')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which the resource appears (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this resource is currently displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Volunteer Resource',
                'verbose_name_plural': 'Volunteer Resources',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
