# Generated by Django 4.2.16 on 2026-02-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0049_volunteerresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_grade_updates',
        ),
    ]
