# Generated by Django 4.2.16 on 2026-05-02 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0053_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'New Post'), ('solution', 'New Solution'), ('comment', 'New Comment'), ('reply', 'New Reply'), ('grade_update', 'Grade Update'), ('edit', 'Post Edit'), ('mention', 'Mention')], max_length=20),
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('solution', 'Solution'), ('comment', 'Comment')], help_text='Type of content containing the mention', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='True if the mention was in anonymous content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='User who made the mention', on_delete=django.db.models.deletion.CASCADE, related_name='mentions_made', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, help_text="If content_type='comment', the comment being mentioned", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='forum.comment')),
                ('mentioned_user', models.ForeignKey(help_text='User who was mentioned', on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, help_text="If content_type='post', the post being mentioned", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='forum.post')),
                ('solution', models.ForeignKey(blank=True, help_text="If content_type='solution', the solution being mentioned", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='forum.solution')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentioned_user', 'created_at'], name='forum_menti_mention_55a514_idx'), models.Index(fields=['author', 'created_at'], name='forum_menti_author__6aa8cc_idx')],
                'unique_together': {('author', 'mentioned_user', 'content_type', 'post', 'solution', 'comment')},
            },
        ),
    ]
