# Generated by Django 4.2.16 on 2026-05-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0047_update_usernames'),
        ('forum', '0054_alter_notification_notification_type_mention'),
    ]

    operations = [
    ]
