# Generated by Django 4.2.16 on 2026-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0055_merge_20260517_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'New Post'), ('solution', 'New Solution'), ('comment', 'New Comment'), ('reply', 'New Reply'), ('grade_update', 'Grade Update'), ('edit', 'Post Edit'), ('mention', 'Mention'), ('channel', 'Channel Mention'), ('everyone', 'Everyone Mention')], max_length=20),
        ),
    ]
