# Generated by Django 4.2.16 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0056_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_msg_app',
            field=models.CharField(
                blank=True,
                choices=[
                    ('insta', 'Instagram'),
                    ('linkedin', 'LinkedIn'),
                    ('snap', 'Snapchat'),
                    ('email', 'Email'),
                    ('discord', 'Discord'),
                ],
                help_text='The app you prefer people to use when contacting you',
                max_length=8,
                null=True,
            ),
        ),
    ]
