# Generated by Django 4.2.16 on 2026-08-22 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0058_update_preferred_msg_app_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=8)),
                ('teacher_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reports', to='forum.course')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_teacher_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['block', 'teacher_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseTeacherVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.courseteacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_report_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseteachervote',
            constraint=models.UniqueConstraint(fields=('teacher_report', 'user'), name='unique_teacher_report_vote'),
        ),
        migrations.AddConstraint(
            model_name='courseteacher',
            constraint=models.UniqueConstraint(fields=('course', 'block', 'teacher_name'), name='unique_course_teacher_report'),
        ),
    ]
