# Generated by Django 4.2.16 on 2026-08-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0061_remove_stale_course_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courseteacher',
            name='submitted_by',
        ),
        migrations.DeleteModel(
            name='CourseTeacherVote',
        ),
    ]
