# Generated by Django 5.1.1 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0068_require_community_lunch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid_user',
            field=models.BooleanField(default=False, help_text='Shows the verified badge for a paid account.'),
        ),
    ]
