# Generated by Django 4.2.16 on 2026-10-05 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0071_copy_moderator_group_to_profiles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userupdateview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userupdateview',
            name='update',
        ),
        migrations.RemoveField(
            model_name='userupdateview',
            name='user',
        ),
        migrations.DeleteModel(
            name='UpdateAnnouncement',
        ),
        migrations.DeleteModel(
            name='UserUpdateView',
        ),
    ]
